// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-rvv-sFMrNLvOYW-6EaLimTAjz3IdPGM',
    appId: '1:650114966729:web:86f4299001440fc1e75918',
    messagingSenderId: '650114966729',
    projectId: 'newproject-ad5bb',
    authDomain: 'newproject-ad5bb.firebaseapp.com',
    storageBucket: 'newproject-ad5bb.firebasestorage.app',
    measurementId: 'G-TV8WS1WNRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp6WsNNGCjtlHhOCQnNzhjh7krE_zw-vQ',
    appId: '1:650114966729:android:3d1ccbd475f14d52e75918',
    messagingSenderId: '650114966729',
    projectId: 'newproject-ad5bb',
    storageBucket: 'newproject-ad5bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaZTVnrdMsDAAQxiiPg6ZxVe3WiDjsgQs',
    appId: '1:650114966729:ios:227b629f13fca61ae75918',
    messagingSenderId: '650114966729',
    projectId: 'newproject-ad5bb',
    storageBucket: 'newproject-ad5bb.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaZTVnrdMsDAAQxiiPg6ZxVe3WiDjsgQs',
    appId: '1:650114966729:ios:227b629f13fca61ae75918',
    messagingSenderId: '650114966729',
    projectId: 'newproject-ad5bb',
    storageBucket: 'newproject-ad5bb.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );
}
